title: Sungur Labs
author: GitHub User
email: 
description: > # this means to ignore newlines until "show_exerpts:"
  This is a project that aims to do security research around low-level area.
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 10
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: sungurlabs-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/sungurlabs
      icon: twitter-square
      color: cyan
    - url: https://github.com/sungurlabs
      icon: github-square
      color: purple

  show_author: true

  animation_speed: 50

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
#- liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
#avatar_source: github
#github_username: bitbrain
avatar_source: local
avatar_path: /assets/avatar.png
